### ISSUE TITLE
go vet: assignment copies lock value to buildLock

### ISSUE THREAD

**Issue by zihangzhen** [hyperledger/fabric#3377]
hello, i want to build fabric in my ubuntu, but i get some problems that i cant find on internet.
i follow the steps in the [doc](https://hyperledger-fabric.readthedocs.io/en/latest/dev-setup/devenv.html#prerequisites). In last topic "Install the development tools", after my typing `make basic-checks integration-test-prereqs`, i get an error like:

`Checking with go vet`
`# github.com/hyperledger/fabric/core/chaincode/lifecycle`
`core/chaincode/lifecycle/lifecycle.go:720:19: assignment copies lock value to buildLock: (sync.Mutex, bool) contains sync.Mutex`
`# github.com/hyperledger/fabric/gossip/privdata`
`gossip/privdata/pull.go:286:4: (github.com/hyperledger/fabric/gossip/util.Logger).Warning call has possible formatting directive %+v`
`make: *** [linter] Error 2`

aslo, i get the same error when my typing `make dist-clean all` on my ubuntu, i just want to build it, pls tell me what should i do, thanks!

my software version like this:
> ubuntu 18.04
> go1.18.1 linux/amd64
> fabric cloned on github
> SoftHSM 2.5.0
> jq 1.5

**Comment by yacovm** [comment]
Thanks, I fixed the issues:

https://github.com/hyperledger/fabric/pull/3378
https://github.com/hyperledger/fabric/pull/3379

**Comment by zihangzhen** [comment]
thanks, the last error is cleared.  But i still get an error like:
`Checking with go vet`
`# github.com/hyperledger/fabric/core/chaincode/lifecycle`
`core/chaincode/lifecycle/lifecycle.go:720:19: assignment copies lock value to buildLock: (sync.Mutex, bool) contains sync.Mutex`
`Makefile:183: recipe for target 'linter' failed`
`make: *** [linter] Error 2`

i wonder konw how to clear this error, thanks!

**Comment by zihangzhen** [comment]
> thanks, the last error is cleared. But i still get an error like: `Checking with go vet` `# github.com/hyperledger/fabric/core/chaincode/lifecycle` `core/chaincode/lifecycle/lifecycle.go:720:19: assignment copies lock value to buildLock: (sync.Mutex, bool) contains sync.Mutex` `Makefile:183: recipe for target 'linter' failed` `make: *** [linter] Error 2`
> 
> i wonder konw how to clear this error, thanks!

sorry, i missed a point, thats ok! thanks!
